### ISSUE TITLE
[feature request] Add option to always save image

### ISSUE THREAD

**Issue by fabiocaseri** [robmarkcole/HASS-Sighthound#19]
Is it possible to add a configuration option (boolean true/false) to always save the image, even when no vehicle/people is found?
At the moment the image is written only if detections are greater than zero.

I use the generated image as a local_file camera in HA, so it can be useful to use the latest image to show the updated situation (in a picture-glance card).

**Comment by robmarkcole** [comment]
I agree I also found it confusing seeing the last image with a detection, rather than the last processed image.

This is a good suggestion, do you want to raise a PR adding the feature?

**Comment by fabiocaseri** [comment]
Sure, I'll try in my spare time.
Is it better to always save last processed image or enable that feature with an additional option?

**Comment by robmarkcole** [comment]
Add an additional config arg: `always_save_latest_jpg` which defaults to `False`, but when `True` will save the image even if there are zero detections

**Comment by alexandrechoske** [comment]
> 
> 
> Add an additional config arg: `always_save_latest_jpg` which defaults to `False`, but when `True` will save the image even if there are zero detections

can you share how to config this? I tried to set this to my configs but got an error.

```
- platform: sighthound
  api_key: !secret sighthound_key
  save_file_folder: /config/tmp
  save_timestamped_file: True
  always_save_latest_jpg: True
  source:
    - entity_id: camera.garagem  
```
`
Invalid config for [image_processing.sighthound]: [always_save_latest_jpg] is an invalid option for [image_processing.sighthound]. Check: image_processing.sighthound->always_save_latest_jpg. (See ?, line ?). `
